# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import policy_pb2 as policy__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/amh.policy.v1.PolicyService/Decide',
                request_serializer=policy__pb2.DecideRequest.SerializeToString,
                response_deserializer=policy__pb2.Decision.FromString,
                _registered_method=True)
        self.GetDecision = channel.unary_unary(
                '/amh.policy.v1.PolicyService/GetDecision',
                request_serializer=policy__pb2.GetDecisionRequest.SerializeToString,
                response_deserializer=policy__pb2.Decision.FromString,
                _registered_method=True)
        self.Consume = channel.unary_unary(
                '/amh.policy.v1.PolicyService/Consume',
                request_serializer=policy__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=policy__pb2.ConsumeResponse.FromString,
                _registered_method=True)
        self.ListPendingApprovals = channel.unary_unary(
                '/amh.policy.v1.PolicyService/ListPendingApprovals',
                request_serializer=policy__pb2.ListPendingApprovalsRequest.SerializeToString,
                response_deserializer=policy__pb2.ListPendingApprovalsResponse.FromString,
                _registered_method=True)
        self.GetApprovalRequest = channel.unary_unary(
                '/amh.policy.v1.PolicyService/GetApprovalRequest',
                request_serializer=policy__pb2.GetApprovalRequestRequest.SerializeToString,
                response_deserializer=policy__pb2.ApprovalRequest.FromString,
                _registered_method=True)
        self.Approve = channel.unary_unary(
                '/amh.policy.v1.PolicyService/Approve',
                request_serializer=policy__pb2.ResolveApprovalRequest.SerializeToString,
                response_deserializer=policy__pb2.Decision.FromString,
                _registered_method=True)
        self.Deny = channel.unary_unary(
                '/amh.policy.v1.PolicyService/Deny',
                request_serializer=policy__pb2.ResolveApprovalRequest.SerializeToString,
                response_deserializer=policy__pb2.ApprovalRequest.FromString,
                _registered_method=True)


class PolicyServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Decide(self, request, context):
        """Decide admits or defers req through the one built-in policy —
        mirrors POST /v1/policy/decide.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecision(self, request, context):
        """GetDecision is a cheap, idempotent read — mirrors
        GET /v1/policy/decisions/{decisionID}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Consume binds dispatch to the exact digest of payload_json, failing
        closed on any mismatch, expiry, or already-consumed decision —
        mirrors POST /v1/policy/decisions/{decisionID}/consume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPendingApprovals(self, request, context):
        """ListPendingApprovals — mirrors GET /v1/policy/approvals.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApprovalRequest(self, request, context):
        """GetApprovalRequest — mirrors GET /v1/policy/approvals/{approvalID}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Approve(self, request, context):
        """Approve is operator-only (enforced by the auth interceptor, the same
        anti-self-approval property daemon/authn's RequireRole already
        enforces over HTTP) — mirrors
        POST /v1/policy/approvals/{approvalID}/approve.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deny(self, request, context):
        """Deny is operator-only — mirrors
        POST /v1/policy/approvals/{approvalID}/deny.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=policy__pb2.DecideRequest.FromString,
                    response_serializer=policy__pb2.Decision.SerializeToString,
            ),
            'GetDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecision,
                    request_deserializer=policy__pb2.GetDecisionRequest.FromString,
                    response_serializer=policy__pb2.Decision.SerializeToString,
            ),
            'Consume': grpc.unary_unary_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=policy__pb2.ConsumeRequest.FromString,
                    response_serializer=policy__pb2.ConsumeResponse.SerializeToString,
            ),
            'ListPendingApprovals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPendingApprovals,
                    request_deserializer=policy__pb2.ListPendingApprovalsRequest.FromString,
                    response_serializer=policy__pb2.ListPendingApprovalsResponse.SerializeToString,
            ),
            'GetApprovalRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApprovalRequest,
                    request_deserializer=policy__pb2.GetApprovalRequestRequest.FromString,
                    response_serializer=policy__pb2.ApprovalRequest.SerializeToString,
            ),
            'Approve': grpc.unary_unary_rpc_method_handler(
                    servicer.Approve,
                    request_deserializer=policy__pb2.ResolveApprovalRequest.FromString,
                    response_serializer=policy__pb2.Decision.SerializeToString,
            ),
            'Deny': grpc.unary_unary_rpc_method_handler(
                    servicer.Deny,
                    request_deserializer=policy__pb2.ResolveApprovalRequest.FromString,
                    response_serializer=policy__pb2.ApprovalRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'amh.policy.v1.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('amh.policy.v1.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.policy.v1.PolicyService/Decide',
            policy__pb2.DecideRequest.SerializeToString,
            policy__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.policy.v1.PolicyService/GetDecision',
            policy__pb2.GetDecisionRequest.SerializeToString,
            policy__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.policy.v1.PolicyService/Consume',
            policy__pb2.ConsumeRequest.SerializeToString,
            policy__pb2.ConsumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPendingApprovals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.policy.v1.PolicyService/ListPendingApprovals',
            policy__pb2.ListPendingApprovalsRequest.SerializeToString,
            policy__pb2.ListPendingApprovalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApprovalRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.policy.v1.PolicyService/GetApprovalRequest',
            policy__pb2.GetApprovalRequestRequest.SerializeToString,
            policy__pb2.ApprovalRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Approve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.policy.v1.PolicyService/Approve',
            policy__pb2.ResolveApprovalRequest.SerializeToString,
            policy__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deny(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.policy.v1.PolicyService/Deny',
            policy__pb2.ResolveApprovalRequest.SerializeToString,
            policy__pb2.ApprovalRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
