# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import selfimprove_pb2 as selfimprove__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in selfimprove_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SelfImproveServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCandidate = channel.unary_unary(
                '/amh.selfimprove.v1.SelfImproveService/GetCandidate',
                request_serializer=selfimprove__pb2.GetCandidateRequest.SerializeToString,
                response_deserializer=selfimprove__pb2.CandidateVersion.FromString,
                _registered_method=True)
        self.ListCandidates = channel.unary_unary(
                '/amh.selfimprove.v1.SelfImproveService/ListCandidates',
                request_serializer=selfimprove__pb2.ListCandidatesRequest.SerializeToString,
                response_deserializer=selfimprove__pb2.ListCandidatesResponse.FromString,
                _registered_method=True)


class SelfImproveServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCandidate(self, request, context):
        """GetCandidate — mirrors GET /v1/selfimprove/candidates/{candidateID}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCandidates(self, request, context):
        """ListCandidates — mirrors GET /v1/selfimprove/candidates, optionally
        filtered by candidate_class and/or status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SelfImproveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandidate,
                    request_deserializer=selfimprove__pb2.GetCandidateRequest.FromString,
                    response_serializer=selfimprove__pb2.CandidateVersion.SerializeToString,
            ),
            'ListCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCandidates,
                    request_deserializer=selfimprove__pb2.ListCandidatesRequest.FromString,
                    response_serializer=selfimprove__pb2.ListCandidatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'amh.selfimprove.v1.SelfImproveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('amh.selfimprove.v1.SelfImproveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SelfImproveService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.selfimprove.v1.SelfImproveService/GetCandidate',
            selfimprove__pb2.GetCandidateRequest.SerializeToString,
            selfimprove__pb2.CandidateVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.selfimprove.v1.SelfImproveService/ListCandidates',
            selfimprove__pb2.ListCandidatesRequest.SerializeToString,
            selfimprove__pb2.ListCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
