# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: selfimprove.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'selfimprove.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11selfimprove.proto\x12\x12\x61mh.selfimprove.v1\"!\n\x13GetCandidateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"@\n\x15ListCandidatesRequest\x12\x17\n\x0f\x63\x61ndidate_class\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"R\n\x16ListCandidatesResponse\x12\x38\n\ncandidates\x18\x01 \x03(\x0b\x32$.amh.selfimprove.v1.CandidateVersion\"\xee\x01\n\x10\x43\x61ndidateVersion\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0f\x63\x61ndidate_class\x18\x02 \x01(\t\x12\x0b\n\x03ref\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x14\n\x0cgenerated_by\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x11\n\tcanary_at\x18\x07 \x01(\t\x12\x13\n\x0bpromoted_at\x18\x08 \x01(\t\x12\x12\n\ndemoted_at\x18\t \x01(\t\x12\x16\n\x0erolled_back_at\x18\n \x01(\t\x12\x1a\n\x12rollback_target_id\x18\x0b \x01(\t2\xdc\x01\n\x12SelfImproveService\x12]\n\x0cGetCandidate\x12\'.amh.selfimprove.v1.GetCandidateRequest\x1a$.amh.selfimprove.v1.CandidateVersion\x12g\n\x0eListCandidates\x12).amh.selfimprove.v1.ListCandidatesRequest\x1a*.amh.selfimprove.v1.ListCandidatesResponseBPZNgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/selfimprovepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'selfimprove_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/selfimprovepb'
  _globals['_GETCANDIDATEREQUEST']._serialized_start=41
  _globals['_GETCANDIDATEREQUEST']._serialized_end=74
  _globals['_LISTCANDIDATESREQUEST']._serialized_start=76
  _globals['_LISTCANDIDATESREQUEST']._serialized_end=140
  _globals['_LISTCANDIDATESRESPONSE']._serialized_start=142
  _globals['_LISTCANDIDATESRESPONSE']._serialized_end=224
  _globals['_CANDIDATEVERSION']._serialized_start=227
  _globals['_CANDIDATEVERSION']._serialized_end=465
  _globals['_SELFIMPROVESERVICE']._serialized_start=468
  _globals['_SELFIMPROVESERVICE']._serialized_end=688
# @@protoc_insertion_point(module_scope)
