// SelfImproveService — daemon/selfimprove's candidate-lifecycle read path
// only (docs/AMH-SPECIFICATION.md §10), over gRPC instead of HTTP+JSON.
//
// Phase 3 of the gRPC migration (see contracts/proto/policy.proto's header
// comment for the migration's overall scope/rationale). Deliberately
// narrower than Phases 1-2: only GetCandidate/ListCandidates move here.
// Those are the only two selfimprove routes with a real internal
// (agent-facing, non-browser, non-external-protocol) Python caller —
// agents/selfimprove/candidates.py's list_candidates/get_promoted_prompt,
// which agents/workflows/goal.py's decompose_goal calls to read a
// promoted "prompt"-class candidate. Every other selfimprove route
// (Generate, RecordEval, Canary, Promote, Demote, Rollback, Reject) is
// either operator-only tooling with no Python client at all, or — for
// Generate — has no real caller yet either; there is no reason to move
// routes nothing here actually calls, so they stay on
// daemon/api/selfimprove.go's existing HTTP surface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: selfimprove.proto

package selfimprovepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateRequest) Reset() {
	*x = GetCandidateRequest{}
	mi := &file_selfimprove_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateRequest) ProtoMessage() {}

func (x *GetCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_selfimprove_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateRequest) Descriptor() ([]byte, []int) {
	return file_selfimprove_proto_rawDescGZIP(), []int{0}
}

func (x *GetCandidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCandidatesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CandidateClass string                 `protobuf:"bytes,1,opt,name=candidate_class,json=candidateClass,proto3" json:"candidate_class,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCandidatesRequest) Reset() {
	*x = ListCandidatesRequest{}
	mi := &file_selfimprove_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesRequest) ProtoMessage() {}

func (x *ListCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_selfimprove_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesRequest.ProtoReflect.Descriptor instead.
func (*ListCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_selfimprove_proto_rawDescGZIP(), []int{1}
}

func (x *ListCandidatesRequest) GetCandidateClass() string {
	if x != nil {
		return x.CandidateClass
	}
	return ""
}

func (x *ListCandidatesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*CandidateVersion    `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCandidatesResponse) Reset() {
	*x = ListCandidatesResponse{}
	mi := &file_selfimprove_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatesResponse) ProtoMessage() {}

func (x *ListCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_selfimprove_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatesResponse.ProtoReflect.Descriptor instead.
func (*ListCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_selfimprove_proto_rawDescGZIP(), []int{2}
}

func (x *ListCandidatesResponse) GetCandidates() []*CandidateVersion {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type CandidateVersion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CandidateClass   string                 `protobuf:"bytes,2,opt,name=candidate_class,json=candidateClass,proto3" json:"candidate_class,omitempty"`
	Ref              string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	GeneratedBy      string                 `protobuf:"bytes,5,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CanaryAt         string                 `protobuf:"bytes,7,opt,name=canary_at,json=canaryAt,proto3" json:"canary_at,omitempty"`
	PromotedAt       string                 `protobuf:"bytes,8,opt,name=promoted_at,json=promotedAt,proto3" json:"promoted_at,omitempty"`
	DemotedAt        string                 `protobuf:"bytes,9,opt,name=demoted_at,json=demotedAt,proto3" json:"demoted_at,omitempty"`
	RolledBackAt     string                 `protobuf:"bytes,10,opt,name=rolled_back_at,json=rolledBackAt,proto3" json:"rolled_back_at,omitempty"`
	RollbackTargetId string                 `protobuf:"bytes,11,opt,name=rollback_target_id,json=rollbackTargetId,proto3" json:"rollback_target_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CandidateVersion) Reset() {
	*x = CandidateVersion{}
	mi := &file_selfimprove_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateVersion) ProtoMessage() {}

func (x *CandidateVersion) ProtoReflect() protoreflect.Message {
	mi := &file_selfimprove_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateVersion.ProtoReflect.Descriptor instead.
func (*CandidateVersion) Descriptor() ([]byte, []int) {
	return file_selfimprove_proto_rawDescGZIP(), []int{3}
}

func (x *CandidateVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CandidateVersion) GetCandidateClass() string {
	if x != nil {
		return x.CandidateClass
	}
	return ""
}

func (x *CandidateVersion) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *CandidateVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CandidateVersion) GetGeneratedBy() string {
	if x != nil {
		return x.GeneratedBy
	}
	return ""
}

func (x *CandidateVersion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CandidateVersion) GetCanaryAt() string {
	if x != nil {
		return x.CanaryAt
	}
	return ""
}

func (x *CandidateVersion) GetPromotedAt() string {
	if x != nil {
		return x.PromotedAt
	}
	return ""
}

func (x *CandidateVersion) GetDemotedAt() string {
	if x != nil {
		return x.DemotedAt
	}
	return ""
}

func (x *CandidateVersion) GetRolledBackAt() string {
	if x != nil {
		return x.RolledBackAt
	}
	return ""
}

func (x *CandidateVersion) GetRollbackTargetId() string {
	if x != nil {
		return x.RollbackTargetId
	}
	return ""
}

var File_selfimprove_proto protoreflect.FileDescriptor

const file_selfimprove_proto_rawDesc = "" +
	"\n" +
	"\x11selfimprove.proto\x12\x12amh.selfimprove.v1\"%\n" +
	"\x13GetCandidateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x15ListCandidatesRequest\x12'\n" +
	"\x0fcandidate_class\x18\x01 \x01(\tR\x0ecandidateClass\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"^\n" +
	"\x16ListCandidatesResponse\x12D\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2$.amh.selfimprove.v1.CandidateVersionR\n" +
	"candidates\"\xe8\x02\n" +
	"\x10CandidateVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fcandidate_class\x18\x02 \x01(\tR\x0ecandidateClass\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fgenerated_by\x18\x05 \x01(\tR\vgeneratedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tcanary_at\x18\a \x01(\tR\bcanaryAt\x12\x1f\n" +
	"\vpromoted_at\x18\b \x01(\tR\n" +
	"promotedAt\x12\x1d\n" +
	"\n" +
	"demoted_at\x18\t \x01(\tR\tdemotedAt\x12$\n" +
	"\x0erolled_back_at\x18\n" +
	" \x01(\tR\frolledBackAt\x12,\n" +
	"\x12rollback_target_id\x18\v \x01(\tR\x10rollbackTargetId2\xdc\x01\n" +
	"\x12SelfImproveService\x12]\n" +
	"\fGetCandidate\x12'.amh.selfimprove.v1.GetCandidateRequest\x1a$.amh.selfimprove.v1.CandidateVersion\x12g\n" +
	"\x0eListCandidates\x12).amh.selfimprove.v1.ListCandidatesRequest\x1a*.amh.selfimprove.v1.ListCandidatesResponseBPZNgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/selfimprovepbb\x06proto3"

var (
	file_selfimprove_proto_rawDescOnce sync.Once
	file_selfimprove_proto_rawDescData []byte
)

func file_selfimprove_proto_rawDescGZIP() []byte {
	file_selfimprove_proto_rawDescOnce.Do(func() {
		file_selfimprove_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_selfimprove_proto_rawDesc), len(file_selfimprove_proto_rawDesc)))
	})
	return file_selfimprove_proto_rawDescData
}

var file_selfimprove_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_selfimprove_proto_goTypes = []any{
	(*GetCandidateRequest)(nil),    // 0: amh.selfimprove.v1.GetCandidateRequest
	(*ListCandidatesRequest)(nil),  // 1: amh.selfimprove.v1.ListCandidatesRequest
	(*ListCandidatesResponse)(nil), // 2: amh.selfimprove.v1.ListCandidatesResponse
	(*CandidateVersion)(nil),       // 3: amh.selfimprove.v1.CandidateVersion
}
var file_selfimprove_proto_depIdxs = []int32{
	3, // 0: amh.selfimprove.v1.ListCandidatesResponse.candidates:type_name -> amh.selfimprove.v1.CandidateVersion
	0, // 1: amh.selfimprove.v1.SelfImproveService.GetCandidate:input_type -> amh.selfimprove.v1.GetCandidateRequest
	1, // 2: amh.selfimprove.v1.SelfImproveService.ListCandidates:input_type -> amh.selfimprove.v1.ListCandidatesRequest
	3, // 3: amh.selfimprove.v1.SelfImproveService.GetCandidate:output_type -> amh.selfimprove.v1.CandidateVersion
	2, // 4: amh.selfimprove.v1.SelfImproveService.ListCandidates:output_type -> amh.selfimprove.v1.ListCandidatesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_selfimprove_proto_init() }
func file_selfimprove_proto_init() {
	if File_selfimprove_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_selfimprove_proto_rawDesc), len(file_selfimprove_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_selfimprove_proto_goTypes,
		DependencyIndexes: file_selfimprove_proto_depIdxs,
		MessageInfos:      file_selfimprove_proto_msgTypes,
	}.Build()
	File_selfimprove_proto = out.File
	file_selfimprove_proto_goTypes = nil
	file_selfimprove_proto_depIdxs = nil
}
