// SelfImproveService — daemon/selfimprove's candidate-lifecycle read path
// only (docs/AMH-SPECIFICATION.md §10), over gRPC instead of HTTP+JSON.
//
// Phase 3 of the gRPC migration (see contracts/proto/policy.proto's header
// comment for the migration's overall scope/rationale). Deliberately
// narrower than Phases 1-2: only GetCandidate/ListCandidates move here.
// Those are the only two selfimprove routes with a real internal
// (agent-facing, non-browser, non-external-protocol) Python caller —
// agents/selfimprove/candidates.py's list_candidates/get_promoted_prompt,
// which agents/workflows/goal.py's decompose_goal calls to read a
// promoted "prompt"-class candidate. Every other selfimprove route
// (Generate, RecordEval, Canary, Promote, Demote, Rollback, Reject) is
// either operator-only tooling with no Python client at all, or — for
// Generate — has no real caller yet either; there is no reason to move
// routes nothing here actually calls, so they stay on
// daemon/api/selfimprove.go's existing HTTP surface.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: selfimprove.proto

package selfimprovepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SelfImproveService_GetCandidate_FullMethodName   = "/amh.selfimprove.v1.SelfImproveService/GetCandidate"
	SelfImproveService_ListCandidates_FullMethodName = "/amh.selfimprove.v1.SelfImproveService/ListCandidates"
)

// SelfImproveServiceClient is the client API for SelfImproveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SelfImproveServiceClient interface {
	// GetCandidate — mirrors GET /v1/selfimprove/candidates/{candidateID}.
	GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*CandidateVersion, error)
	// ListCandidates — mirrors GET /v1/selfimprove/candidates, optionally
	// filtered by candidate_class and/or status.
	ListCandidates(ctx context.Context, in *ListCandidatesRequest, opts ...grpc.CallOption) (*ListCandidatesResponse, error)
}

type selfImproveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSelfImproveServiceClient(cc grpc.ClientConnInterface) SelfImproveServiceClient {
	return &selfImproveServiceClient{cc}
}

func (c *selfImproveServiceClient) GetCandidate(ctx context.Context, in *GetCandidateRequest, opts ...grpc.CallOption) (*CandidateVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CandidateVersion)
	err := c.cc.Invoke(ctx, SelfImproveService_GetCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfImproveServiceClient) ListCandidates(ctx context.Context, in *ListCandidatesRequest, opts ...grpc.CallOption) (*ListCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCandidatesResponse)
	err := c.cc.Invoke(ctx, SelfImproveService_ListCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelfImproveServiceServer is the server API for SelfImproveService service.
// All implementations must embed UnimplementedSelfImproveServiceServer
// for forward compatibility.
type SelfImproveServiceServer interface {
	// GetCandidate — mirrors GET /v1/selfimprove/candidates/{candidateID}.
	GetCandidate(context.Context, *GetCandidateRequest) (*CandidateVersion, error)
	// ListCandidates — mirrors GET /v1/selfimprove/candidates, optionally
	// filtered by candidate_class and/or status.
	ListCandidates(context.Context, *ListCandidatesRequest) (*ListCandidatesResponse, error)
	mustEmbedUnimplementedSelfImproveServiceServer()
}

// UnimplementedSelfImproveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSelfImproveServiceServer struct{}

func (UnimplementedSelfImproveServiceServer) GetCandidate(context.Context, *GetCandidateRequest) (*CandidateVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedSelfImproveServiceServer) ListCandidates(context.Context, *ListCandidatesRequest) (*ListCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCandidates not implemented")
}
func (UnimplementedSelfImproveServiceServer) mustEmbedUnimplementedSelfImproveServiceServer() {}
func (UnimplementedSelfImproveServiceServer) testEmbeddedByValue()                            {}

// UnsafeSelfImproveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelfImproveServiceServer will
// result in compilation errors.
type UnsafeSelfImproveServiceServer interface {
	mustEmbedUnimplementedSelfImproveServiceServer()
}

func RegisterSelfImproveServiceServer(s grpc.ServiceRegistrar, srv SelfImproveServiceServer) {
	// If the following call panics, it indicates UnimplementedSelfImproveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SelfImproveService_ServiceDesc, srv)
}

func _SelfImproveService_GetCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfImproveServiceServer).GetCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfImproveService_GetCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfImproveServiceServer).GetCandidate(ctx, req.(*GetCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfImproveService_ListCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfImproveServiceServer).ListCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfImproveService_ListCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfImproveServiceServer).ListCandidates(ctx, req.(*ListCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SelfImproveService_ServiceDesc is the grpc.ServiceDesc for SelfImproveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SelfImproveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amh.selfimprove.v1.SelfImproveService",
	HandlerType: (*SelfImproveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCandidate",
			Handler:    _SelfImproveService_GetCandidate_Handler,
		},
		{
			MethodName: "ListCandidates",
			Handler:    _SelfImproveService_ListCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "selfimprove.proto",
}
