# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import operations_pb2 as operations__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperationsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Propose = channel.unary_unary(
                '/amh.operations.v1.OperationsService/Propose',
                request_serializer=operations__pb2.ProposeRequest.SerializeToString,
                response_deserializer=operations__pb2.Effect.FromString,
                _registered_method=True)
        self.GetEffect = channel.unary_unary(
                '/amh.operations.v1.OperationsService/GetEffect',
                request_serializer=operations__pb2.GetEffectRequest.SerializeToString,
                response_deserializer=operations__pb2.Effect.FromString,
                _registered_method=True)
        self.ListEffectsByOperation = channel.unary_unary(
                '/amh.operations.v1.OperationsService/ListEffectsByOperation',
                request_serializer=operations__pb2.ListEffectsByOperationRequest.SerializeToString,
                response_deserializer=operations__pb2.ListEffectsByOperationResponse.FromString,
                _registered_method=True)
        self.MarkDispatchPending = channel.unary_unary(
                '/amh.operations.v1.OperationsService/MarkDispatchPending',
                request_serializer=operations__pb2.MarkDispatchPendingRequest.SerializeToString,
                response_deserializer=operations__pb2.Effect.FromString,
                _registered_method=True)
        self.MarkDispatched = channel.unary_unary(
                '/amh.operations.v1.OperationsService/MarkDispatched',
                request_serializer=operations__pb2.MarkDispatchedRequest.SerializeToString,
                response_deserializer=operations__pb2.Effect.FromString,
                _registered_method=True)
        self.MarkObserved = channel.unary_unary(
                '/amh.operations.v1.OperationsService/MarkObserved',
                request_serializer=operations__pb2.MarkObservedRequest.SerializeToString,
                response_deserializer=operations__pb2.Effect.FromString,
                _registered_method=True)
        self.MarkOutcomeUnknown = channel.unary_unary(
                '/amh.operations.v1.OperationsService/MarkOutcomeUnknown',
                request_serializer=operations__pb2.MarkOutcomeUnknownRequest.SerializeToString,
                response_deserializer=operations__pb2.Effect.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/amh.operations.v1.OperationsService/Resolve',
                request_serializer=operations__pb2.ResolveRequest.SerializeToString,
                response_deserializer=operations__pb2.Effect.FromString,
                _registered_method=True)


class OperationsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Propose(self, request, context):
        """Propose creates a new effect record and runs it through daemon/policy
        for admission — mirrors POST /v1/operations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEffect(self, request, context):
        """GetEffect is a cheap, idempotent read — mirrors
        GET /v1/operations/{effectID}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEffectsByOperation(self, request, context):
        """ListEffectsByOperation — mirrors GET /v1/operations?operation_id=....
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkDispatchPending(self, request, context):
        """MarkDispatchPending atomically consumes the admitting PolicyDecision,
        binding dispatch to dispatch_payload_json's exact digest — mirrors
        POST /v1/operations/{effectID}/dispatch-pending.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkDispatched(self, request, context):
        """MarkDispatched — mirrors POST /v1/operations/{effectID}/dispatched.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkObserved(self, request, context):
        """MarkObserved — mirrors POST /v1/operations/{effectID}/observed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkOutcomeUnknown(self, request, context):
        """MarkOutcomeUnknown — mirrors
        POST /v1/operations/{effectID}/outcome-unknown.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """Resolve records the caller's own terminal verdict — mirrors
        POST /v1/operations/{effectID}/resolve. See daemon/operations's doc
        comment for why this argument is trusted from the caller rather than
        computed server-side, the deliberate exception to this codebase's
        usual never-trust-the-caller posture.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=operations__pb2.ProposeRequest.FromString,
                    response_serializer=operations__pb2.Effect.SerializeToString,
            ),
            'GetEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEffect,
                    request_deserializer=operations__pb2.GetEffectRequest.FromString,
                    response_serializer=operations__pb2.Effect.SerializeToString,
            ),
            'ListEffectsByOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEffectsByOperation,
                    request_deserializer=operations__pb2.ListEffectsByOperationRequest.FromString,
                    response_serializer=operations__pb2.ListEffectsByOperationResponse.SerializeToString,
            ),
            'MarkDispatchPending': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkDispatchPending,
                    request_deserializer=operations__pb2.MarkDispatchPendingRequest.FromString,
                    response_serializer=operations__pb2.Effect.SerializeToString,
            ),
            'MarkDispatched': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkDispatched,
                    request_deserializer=operations__pb2.MarkDispatchedRequest.FromString,
                    response_serializer=operations__pb2.Effect.SerializeToString,
            ),
            'MarkObserved': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkObserved,
                    request_deserializer=operations__pb2.MarkObservedRequest.FromString,
                    response_serializer=operations__pb2.Effect.SerializeToString,
            ),
            'MarkOutcomeUnknown': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkOutcomeUnknown,
                    request_deserializer=operations__pb2.MarkOutcomeUnknownRequest.FromString,
                    response_serializer=operations__pb2.Effect.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=operations__pb2.ResolveRequest.FromString,
                    response_serializer=operations__pb2.Effect.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'amh.operations.v1.OperationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('amh.operations.v1.OperationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/Propose',
            operations__pb2.ProposeRequest.SerializeToString,
            operations__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/GetEffect',
            operations__pb2.GetEffectRequest.SerializeToString,
            operations__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEffectsByOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/ListEffectsByOperation',
            operations__pb2.ListEffectsByOperationRequest.SerializeToString,
            operations__pb2.ListEffectsByOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkDispatchPending(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/MarkDispatchPending',
            operations__pb2.MarkDispatchPendingRequest.SerializeToString,
            operations__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkDispatched(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/MarkDispatched',
            operations__pb2.MarkDispatchedRequest.SerializeToString,
            operations__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkObserved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/MarkObserved',
            operations__pb2.MarkObservedRequest.SerializeToString,
            operations__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkOutcomeUnknown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/MarkOutcomeUnknown',
            operations__pb2.MarkOutcomeUnknownRequest.SerializeToString,
            operations__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.operations.v1.OperationsService/Resolve',
            operations__pb2.ResolveRequest.SerializeToString,
            operations__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
