// OperationsService — daemon/operations's generic external-effect
// lifecycle (docs/AMH-SPECIFICATION.md §4), over gRPC instead of HTTP+JSON.
//
// Phase 2 of the gRPC migration (see contracts/proto/policy.proto's header
// comment for the migration's overall scope/rationale; this is the same
// posture applied to the next service). operations has no browser
// (control-plane UI) caller and no external-protocol caller — its real
// callers are Python agent code (agents/workflows/operations.py, the sole
// production call site being harness/agentic_loop.py's MCP tool-call
// tracking) and, in-process on the Go side, daemon/extensions and
// daemon/inference, which already call daemon/operations.Engine directly
// without going through any HTTP/gRPC hop at all.
//
// payload_json stays a JSON-encoded string, not google.protobuf.Struct,
// for the same reason policy.proto's payload_json does: MarkDispatchPending
// hashes the dispatch-time payload fresh and binds it to the digest
// Propose already admitted (§15 acceptance invariant #6), and that digest
// must be computed identically regardless of which transport carried the
// call.
//
// Effect-ownership authorization (§15 acceptance invariant #5: "an
// extension cannot mutate another extension's owned effects") is NOT
// expressed as a per-method role allow-list the way policy.proto's
// operator-only Approve/Deny are — daemon/authn only has two static,
// global roles, and this check is per-effect, not per-route. It works the
// same way over gRPC as it does over HTTP
// (daemon/api/operations.go's authorizeEffectOwner/authorizeEffectMutation):
// an operator token always passes; an owner_extension_id under the
// "amh.core/" prefix passes with nothing more than the ordinary
// agent-or-operator check every method already has; anything else
// requires the caller to present that exact extension's own capability
// token (minted at Activate — daemon/extensions/capability.go) as gRPC
// metadata key "x-amh-extension-token", the metadata analog of the HTTP
// client's X-AMH-Extension-Token header.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: operations.proto

package operationspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationsService_Propose_FullMethodName                = "/amh.operations.v1.OperationsService/Propose"
	OperationsService_GetEffect_FullMethodName              = "/amh.operations.v1.OperationsService/GetEffect"
	OperationsService_ListEffectsByOperation_FullMethodName = "/amh.operations.v1.OperationsService/ListEffectsByOperation"
	OperationsService_MarkDispatchPending_FullMethodName    = "/amh.operations.v1.OperationsService/MarkDispatchPending"
	OperationsService_MarkDispatched_FullMethodName         = "/amh.operations.v1.OperationsService/MarkDispatched"
	OperationsService_MarkObserved_FullMethodName           = "/amh.operations.v1.OperationsService/MarkObserved"
	OperationsService_MarkOutcomeUnknown_FullMethodName     = "/amh.operations.v1.OperationsService/MarkOutcomeUnknown"
	OperationsService_Resolve_FullMethodName                = "/amh.operations.v1.OperationsService/Resolve"
)

// OperationsServiceClient is the client API for OperationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperationsServiceClient interface {
	// Propose creates a new effect record and runs it through daemon/policy
	// for admission — mirrors POST /v1/operations.
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*Effect, error)
	// GetEffect is a cheap, idempotent read — mirrors
	// GET /v1/operations/{effectID}.
	GetEffect(ctx context.Context, in *GetEffectRequest, opts ...grpc.CallOption) (*Effect, error)
	// ListEffectsByOperation — mirrors GET /v1/operations?operation_id=....
	ListEffectsByOperation(ctx context.Context, in *ListEffectsByOperationRequest, opts ...grpc.CallOption) (*ListEffectsByOperationResponse, error)
	// MarkDispatchPending atomically consumes the admitting PolicyDecision,
	// binding dispatch to dispatch_payload_json's exact digest — mirrors
	// POST /v1/operations/{effectID}/dispatch-pending.
	MarkDispatchPending(ctx context.Context, in *MarkDispatchPendingRequest, opts ...grpc.CallOption) (*Effect, error)
	// MarkDispatched — mirrors POST /v1/operations/{effectID}/dispatched.
	MarkDispatched(ctx context.Context, in *MarkDispatchedRequest, opts ...grpc.CallOption) (*Effect, error)
	// MarkObserved — mirrors POST /v1/operations/{effectID}/observed.
	MarkObserved(ctx context.Context, in *MarkObservedRequest, opts ...grpc.CallOption) (*Effect, error)
	// MarkOutcomeUnknown — mirrors
	// POST /v1/operations/{effectID}/outcome-unknown.
	MarkOutcomeUnknown(ctx context.Context, in *MarkOutcomeUnknownRequest, opts ...grpc.CallOption) (*Effect, error)
	// Resolve records the caller's own terminal verdict — mirrors
	// POST /v1/operations/{effectID}/resolve. See daemon/operations's doc
	// comment for why this argument is trusted from the caller rather than
	// computed server-side, the deliberate exception to this codebase's
	// usual never-trust-the-caller posture.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*Effect, error)
}

type operationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationsServiceClient(cc grpc.ClientConnInterface) OperationsServiceClient {
	return &operationsServiceClient{cc}
}

func (c *operationsServiceClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*Effect, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effect)
	err := c.cc.Invoke(ctx, OperationsService_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) GetEffect(ctx context.Context, in *GetEffectRequest, opts ...grpc.CallOption) (*Effect, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effect)
	err := c.cc.Invoke(ctx, OperationsService_GetEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) ListEffectsByOperation(ctx context.Context, in *ListEffectsByOperationRequest, opts ...grpc.CallOption) (*ListEffectsByOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEffectsByOperationResponse)
	err := c.cc.Invoke(ctx, OperationsService_ListEffectsByOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) MarkDispatchPending(ctx context.Context, in *MarkDispatchPendingRequest, opts ...grpc.CallOption) (*Effect, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effect)
	err := c.cc.Invoke(ctx, OperationsService_MarkDispatchPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) MarkDispatched(ctx context.Context, in *MarkDispatchedRequest, opts ...grpc.CallOption) (*Effect, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effect)
	err := c.cc.Invoke(ctx, OperationsService_MarkDispatched_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) MarkObserved(ctx context.Context, in *MarkObservedRequest, opts ...grpc.CallOption) (*Effect, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effect)
	err := c.cc.Invoke(ctx, OperationsService_MarkObserved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) MarkOutcomeUnknown(ctx context.Context, in *MarkOutcomeUnknownRequest, opts ...grpc.CallOption) (*Effect, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effect)
	err := c.cc.Invoke(ctx, OperationsService_MarkOutcomeUnknown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*Effect, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Effect)
	err := c.cc.Invoke(ctx, OperationsService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationsServiceServer is the server API for OperationsService service.
// All implementations must embed UnimplementedOperationsServiceServer
// for forward compatibility.
type OperationsServiceServer interface {
	// Propose creates a new effect record and runs it through daemon/policy
	// for admission — mirrors POST /v1/operations.
	Propose(context.Context, *ProposeRequest) (*Effect, error)
	// GetEffect is a cheap, idempotent read — mirrors
	// GET /v1/operations/{effectID}.
	GetEffect(context.Context, *GetEffectRequest) (*Effect, error)
	// ListEffectsByOperation — mirrors GET /v1/operations?operation_id=....
	ListEffectsByOperation(context.Context, *ListEffectsByOperationRequest) (*ListEffectsByOperationResponse, error)
	// MarkDispatchPending atomically consumes the admitting PolicyDecision,
	// binding dispatch to dispatch_payload_json's exact digest — mirrors
	// POST /v1/operations/{effectID}/dispatch-pending.
	MarkDispatchPending(context.Context, *MarkDispatchPendingRequest) (*Effect, error)
	// MarkDispatched — mirrors POST /v1/operations/{effectID}/dispatched.
	MarkDispatched(context.Context, *MarkDispatchedRequest) (*Effect, error)
	// MarkObserved — mirrors POST /v1/operations/{effectID}/observed.
	MarkObserved(context.Context, *MarkObservedRequest) (*Effect, error)
	// MarkOutcomeUnknown — mirrors
	// POST /v1/operations/{effectID}/outcome-unknown.
	MarkOutcomeUnknown(context.Context, *MarkOutcomeUnknownRequest) (*Effect, error)
	// Resolve records the caller's own terminal verdict — mirrors
	// POST /v1/operations/{effectID}/resolve. See daemon/operations's doc
	// comment for why this argument is trusted from the caller rather than
	// computed server-side, the deliberate exception to this codebase's
	// usual never-trust-the-caller posture.
	Resolve(context.Context, *ResolveRequest) (*Effect, error)
	mustEmbedUnimplementedOperationsServiceServer()
}

// UnimplementedOperationsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationsServiceServer struct{}

func (UnimplementedOperationsServiceServer) Propose(context.Context, *ProposeRequest) (*Effect, error) {
	return nil, status.Error(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedOperationsServiceServer) GetEffect(context.Context, *GetEffectRequest) (*Effect, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEffect not implemented")
}
func (UnimplementedOperationsServiceServer) ListEffectsByOperation(context.Context, *ListEffectsByOperationRequest) (*ListEffectsByOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEffectsByOperation not implemented")
}
func (UnimplementedOperationsServiceServer) MarkDispatchPending(context.Context, *MarkDispatchPendingRequest) (*Effect, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkDispatchPending not implemented")
}
func (UnimplementedOperationsServiceServer) MarkDispatched(context.Context, *MarkDispatchedRequest) (*Effect, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkDispatched not implemented")
}
func (UnimplementedOperationsServiceServer) MarkObserved(context.Context, *MarkObservedRequest) (*Effect, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkObserved not implemented")
}
func (UnimplementedOperationsServiceServer) MarkOutcomeUnknown(context.Context, *MarkOutcomeUnknownRequest) (*Effect, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkOutcomeUnknown not implemented")
}
func (UnimplementedOperationsServiceServer) Resolve(context.Context, *ResolveRequest) (*Effect, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedOperationsServiceServer) mustEmbedUnimplementedOperationsServiceServer() {}
func (UnimplementedOperationsServiceServer) testEmbeddedByValue()                           {}

// UnsafeOperationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationsServiceServer will
// result in compilation errors.
type UnsafeOperationsServiceServer interface {
	mustEmbedUnimplementedOperationsServiceServer()
}

func RegisterOperationsServiceServer(s grpc.ServiceRegistrar, srv OperationsServiceServer) {
	// If the following call panics, it indicates UnimplementedOperationsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationsService_ServiceDesc, srv)
}

func _OperationsService_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_GetEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).GetEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_GetEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).GetEffect(ctx, req.(*GetEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_ListEffectsByOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEffectsByOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).ListEffectsByOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_ListEffectsByOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).ListEffectsByOperation(ctx, req.(*ListEffectsByOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_MarkDispatchPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkDispatchPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).MarkDispatchPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_MarkDispatchPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).MarkDispatchPending(ctx, req.(*MarkDispatchPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_MarkDispatched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkDispatchedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).MarkDispatched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_MarkDispatched_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).MarkDispatched(ctx, req.(*MarkDispatchedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_MarkObserved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkObservedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).MarkObserved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_MarkObserved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).MarkObserved(ctx, req.(*MarkObservedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_MarkOutcomeUnknown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkOutcomeUnknownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).MarkOutcomeUnknown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_MarkOutcomeUnknown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).MarkOutcomeUnknown(ctx, req.(*MarkOutcomeUnknownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationsService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationsService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationsService_ServiceDesc is the grpc.ServiceDesc for OperationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amh.operations.v1.OperationsService",
	HandlerType: (*OperationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _OperationsService_Propose_Handler,
		},
		{
			MethodName: "GetEffect",
			Handler:    _OperationsService_GetEffect_Handler,
		},
		{
			MethodName: "ListEffectsByOperation",
			Handler:    _OperationsService_ListEffectsByOperation_Handler,
		},
		{
			MethodName: "MarkDispatchPending",
			Handler:    _OperationsService_MarkDispatchPending_Handler,
		},
		{
			MethodName: "MarkDispatched",
			Handler:    _OperationsService_MarkDispatched_Handler,
		},
		{
			MethodName: "MarkObserved",
			Handler:    _OperationsService_MarkObserved_Handler,
		},
		{
			MethodName: "MarkOutcomeUnknown",
			Handler:    _OperationsService_MarkOutcomeUnknown_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _OperationsService_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operations.proto",
}
