// OperationsService — daemon/operations's generic external-effect
// lifecycle (docs/AMH-SPECIFICATION.md §4), over gRPC instead of HTTP+JSON.
//
// Phase 2 of the gRPC migration (see contracts/proto/policy.proto's header
// comment for the migration's overall scope/rationale; this is the same
// posture applied to the next service). operations has no browser
// (control-plane UI) caller and no external-protocol caller — its real
// callers are Python agent code (agents/workflows/operations.py, the sole
// production call site being harness/agentic_loop.py's MCP tool-call
// tracking) and, in-process on the Go side, daemon/extensions and
// daemon/inference, which already call daemon/operations.Engine directly
// without going through any HTTP/gRPC hop at all.
//
// payload_json stays a JSON-encoded string, not google.protobuf.Struct,
// for the same reason policy.proto's payload_json does: MarkDispatchPending
// hashes the dispatch-time payload fresh and binds it to the digest
// Propose already admitted (§15 acceptance invariant #6), and that digest
// must be computed identically regardless of which transport carried the
// call.
//
// Effect-ownership authorization (§15 acceptance invariant #5: "an
// extension cannot mutate another extension's owned effects") is NOT
// expressed as a per-method role allow-list the way policy.proto's
// operator-only Approve/Deny are — daemon/authn only has two static,
// global roles, and this check is per-effect, not per-route. It works the
// same way over gRPC as it does over HTTP
// (daemon/api/operations.go's authorizeEffectOwner/authorizeEffectMutation):
// an operator token always passes; an owner_extension_id under the
// "amh.core/" prefix passes with nothing more than the ordinary
// agent-or-operator check every method already has; anything else
// requires the caller to present that exact extension's own capability
// token (minted at Activate — daemon/extensions/capability.go) as gRPC
// metadata key "x-amh-extension-token", the metadata analog of the HTTP
// client's X-AMH-Extension-Token header.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: operations.proto

package operationspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OwnerExtensionId string                 `protobuf:"bytes,2,opt,name=owner_extension_id,json=ownerExtensionId,proto3" json:"owner_extension_id,omitempty"`
	EffectType       string                 `protobuf:"bytes,3,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`
	PayloadJson      string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Reversibility    string                 `protobuf:"bytes,5,opt,name=reversibility,proto3" json:"reversibility,omitempty"`
	RetryClass       string                 `protobuf:"bytes,6,opt,name=retry_class,json=retryClass,proto3" json:"retry_class,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProposeRequest) Reset() {
	*x = ProposeRequest{}
	mi := &file_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRequest) ProtoMessage() {}

func (x *ProposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRequest.ProtoReflect.Descriptor instead.
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{0}
}

func (x *ProposeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ProposeRequest) GetOwnerExtensionId() string {
	if x != nil {
		return x.OwnerExtensionId
	}
	return ""
}

func (x *ProposeRequest) GetEffectType() string {
	if x != nil {
		return x.EffectType
	}
	return ""
}

func (x *ProposeRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *ProposeRequest) GetReversibility() string {
	if x != nil {
		return x.Reversibility
	}
	return ""
}

func (x *ProposeRequest) GetRetryClass() string {
	if x != nil {
		return x.RetryClass
	}
	return ""
}

type GetEffectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectId      string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectRequest) Reset() {
	*x = GetEffectRequest{}
	mi := &file_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectRequest) ProtoMessage() {}

func (x *GetEffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectRequest.ProtoReflect.Descriptor instead.
func (*GetEffectRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{1}
}

func (x *GetEffectRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

type ListEffectsByOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEffectsByOperationRequest) Reset() {
	*x = ListEffectsByOperationRequest{}
	mi := &file_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEffectsByOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEffectsByOperationRequest) ProtoMessage() {}

func (x *ListEffectsByOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEffectsByOperationRequest.ProtoReflect.Descriptor instead.
func (*ListEffectsByOperationRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{2}
}

func (x *ListEffectsByOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ListEffectsByOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effects       []*Effect              `protobuf:"bytes,1,rep,name=effects,proto3" json:"effects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEffectsByOperationResponse) Reset() {
	*x = ListEffectsByOperationResponse{}
	mi := &file_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEffectsByOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEffectsByOperationResponse) ProtoMessage() {}

func (x *ListEffectsByOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEffectsByOperationResponse.ProtoReflect.Descriptor instead.
func (*ListEffectsByOperationResponse) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{3}
}

func (x *ListEffectsByOperationResponse) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

type MarkDispatchPendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectId      string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkDispatchPendingRequest) Reset() {
	*x = MarkDispatchPendingRequest{}
	mi := &file_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkDispatchPendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkDispatchPendingRequest) ProtoMessage() {}

func (x *MarkDispatchPendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkDispatchPendingRequest.ProtoReflect.Descriptor instead.
func (*MarkDispatchPendingRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{4}
}

func (x *MarkDispatchPendingRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *MarkDispatchPendingRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type MarkDispatchedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EffectId          string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	ExternalCommandId string                 `protobuf:"bytes,2,opt,name=external_command_id,json=externalCommandId,proto3" json:"external_command_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MarkDispatchedRequest) Reset() {
	*x = MarkDispatchedRequest{}
	mi := &file_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkDispatchedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkDispatchedRequest) ProtoMessage() {}

func (x *MarkDispatchedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkDispatchedRequest.ProtoReflect.Descriptor instead.
func (*MarkDispatchedRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{5}
}

func (x *MarkDispatchedRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *MarkDispatchedRequest) GetExternalCommandId() string {
	if x != nil {
		return x.ExternalCommandId
	}
	return ""
}

type MarkObservedRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EffectId           string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	ObservationRef     string                 `protobuf:"bytes,2,opt,name=observation_ref,json=observationRef,proto3" json:"observation_ref,omitempty"`
	ObservationPayload string                 `protobuf:"bytes,3,opt,name=observation_payload,json=observationPayload,proto3" json:"observation_payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MarkObservedRequest) Reset() {
	*x = MarkObservedRequest{}
	mi := &file_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkObservedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkObservedRequest) ProtoMessage() {}

func (x *MarkObservedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkObservedRequest.ProtoReflect.Descriptor instead.
func (*MarkObservedRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{6}
}

func (x *MarkObservedRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *MarkObservedRequest) GetObservationRef() string {
	if x != nil {
		return x.ObservationRef
	}
	return ""
}

func (x *MarkObservedRequest) GetObservationPayload() string {
	if x != nil {
		return x.ObservationPayload
	}
	return ""
}

type MarkOutcomeUnknownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectId      string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOutcomeUnknownRequest) Reset() {
	*x = MarkOutcomeUnknownRequest{}
	mi := &file_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOutcomeUnknownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOutcomeUnknownRequest) ProtoMessage() {}

func (x *MarkOutcomeUnknownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOutcomeUnknownRequest.ProtoReflect.Descriptor instead.
func (*MarkOutcomeUnknownRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{7}
}

func (x *MarkOutcomeUnknownRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectId      string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	Terminal      string                 `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveRequest) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *ResolveRequest) GetTerminal() string {
	if x != nil {
		return x.Terminal
	}
	return ""
}

func (x *ResolveRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ResolveRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ResolveRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Effect struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EffectId           string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	OperationId        string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	OwnerExtensionId   string                 `protobuf:"bytes,3,opt,name=owner_extension_id,json=ownerExtensionId,proto3" json:"owner_extension_id,omitempty"`
	EffectType         string                 `protobuf:"bytes,4,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`
	DecisionId         string                 `protobuf:"bytes,5,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	State              string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	ForwardDigest      string                 `protobuf:"bytes,7,opt,name=forward_digest,json=forwardDigest,proto3" json:"forward_digest,omitempty"`
	RetryClass         string                 `protobuf:"bytes,8,opt,name=retry_class,json=retryClass,proto3" json:"retry_class,omitempty"`
	ExternalCommandId  string                 `protobuf:"bytes,9,opt,name=external_command_id,json=externalCommandId,proto3" json:"external_command_id,omitempty"`
	ObservationRef     string                 `protobuf:"bytes,10,opt,name=observation_ref,json=observationRef,proto3" json:"observation_ref,omitempty"`
	ObservationPayload string                 `protobuf:"bytes,11,opt,name=observation_payload,json=observationPayload,proto3" json:"observation_payload,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,12,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorRetryable     bool                   `protobuf:"varint,13,opt,name=error_retryable,json=errorRetryable,proto3" json:"error_retryable,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,14,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_operations_proto_rawDescGZIP(), []int{9}
}

func (x *Effect) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *Effect) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Effect) GetOwnerExtensionId() string {
	if x != nil {
		return x.OwnerExtensionId
	}
	return ""
}

func (x *Effect) GetEffectType() string {
	if x != nil {
		return x.EffectType
	}
	return ""
}

func (x *Effect) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Effect) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Effect) GetForwardDigest() string {
	if x != nil {
		return x.ForwardDigest
	}
	return ""
}

func (x *Effect) GetRetryClass() string {
	if x != nil {
		return x.RetryClass
	}
	return ""
}

func (x *Effect) GetExternalCommandId() string {
	if x != nil {
		return x.ExternalCommandId
	}
	return ""
}

func (x *Effect) GetObservationRef() string {
	if x != nil {
		return x.ObservationRef
	}
	return ""
}

func (x *Effect) GetObservationPayload() string {
	if x != nil {
		return x.ObservationPayload
	}
	return ""
}

func (x *Effect) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Effect) GetErrorRetryable() bool {
	if x != nil {
		return x.ErrorRetryable
	}
	return false
}

func (x *Effect) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Effect) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Effect) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_operations_proto protoreflect.FileDescriptor

const file_operations_proto_rawDesc = "" +
	"\n" +
	"\x10operations.proto\x12\x11amh.operations.v1\"\xec\x01\n" +
	"\x0eProposeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12,\n" +
	"\x12owner_extension_id\x18\x02 \x01(\tR\x10ownerExtensionId\x12\x1f\n" +
	"\veffect_type\x18\x03 \x01(\tR\n" +
	"effectType\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12$\n" +
	"\rreversibility\x18\x05 \x01(\tR\rreversibility\x12\x1f\n" +
	"\vretry_class\x18\x06 \x01(\tR\n" +
	"retryClass\"/\n" +
	"\x10GetEffectRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\"B\n" +
	"\x1dListEffectsByOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"U\n" +
	"\x1eListEffectsByOperationResponse\x123\n" +
	"\aeffects\x18\x01 \x03(\v2\x19.amh.operations.v1.EffectR\aeffects\"\\\n" +
	"\x1aMarkDispatchPendingRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"d\n" +
	"\x15MarkDispatchedRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12.\n" +
	"\x13external_command_id\x18\x02 \x01(\tR\x11externalCommandId\"\x8c\x01\n" +
	"\x13MarkObservedRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12'\n" +
	"\x0fobservation_ref\x18\x02 \x01(\tR\x0eobservationRef\x12/\n" +
	"\x13observation_payload\x18\x03 \x01(\tR\x12observationPayload\"8\n" +
	"\x19MarkOutcomeUnknownRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\"\xa0\x01\n" +
	"\x0eResolveRequest\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12\x1a\n" +
	"\bterminal\x18\x02 \x01(\tR\bterminal\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xcb\x04\n" +
	"\x06Effect\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12,\n" +
	"\x12owner_extension_id\x18\x03 \x01(\tR\x10ownerExtensionId\x12\x1f\n" +
	"\veffect_type\x18\x04 \x01(\tR\n" +
	"effectType\x12\x1f\n" +
	"\vdecision_id\x18\x05 \x01(\tR\n" +
	"decisionId\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12%\n" +
	"\x0eforward_digest\x18\a \x01(\tR\rforwardDigest\x12\x1f\n" +
	"\vretry_class\x18\b \x01(\tR\n" +
	"retryClass\x12.\n" +
	"\x13external_command_id\x18\t \x01(\tR\x11externalCommandId\x12'\n" +
	"\x0fobservation_ref\x18\n" +
	" \x01(\tR\x0eobservationRef\x12/\n" +
	"\x13observation_payload\x18\v \x01(\tR\x12observationPayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\f \x01(\tR\terrorCode\x12'\n" +
	"\x0ferror_retryable\x18\r \x01(\bR\x0eerrorRetryable\x12#\n" +
	"\rerror_message\x18\x0e \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt2\xdb\x05\n" +
	"\x11OperationsService\x12G\n" +
	"\aPropose\x12!.amh.operations.v1.ProposeRequest\x1a\x19.amh.operations.v1.Effect\x12K\n" +
	"\tGetEffect\x12#.amh.operations.v1.GetEffectRequest\x1a\x19.amh.operations.v1.Effect\x12}\n" +
	"\x16ListEffectsByOperation\x120.amh.operations.v1.ListEffectsByOperationRequest\x1a1.amh.operations.v1.ListEffectsByOperationResponse\x12_\n" +
	"\x13MarkDispatchPending\x12-.amh.operations.v1.MarkDispatchPendingRequest\x1a\x19.amh.operations.v1.Effect\x12U\n" +
	"\x0eMarkDispatched\x12(.amh.operations.v1.MarkDispatchedRequest\x1a\x19.amh.operations.v1.Effect\x12Q\n" +
	"\fMarkObserved\x12&.amh.operations.v1.MarkObservedRequest\x1a\x19.amh.operations.v1.Effect\x12]\n" +
	"\x12MarkOutcomeUnknown\x12,.amh.operations.v1.MarkOutcomeUnknownRequest\x1a\x19.amh.operations.v1.Effect\x12G\n" +
	"\aResolve\x12!.amh.operations.v1.ResolveRequest\x1a\x19.amh.operations.v1.EffectBOZMgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/operationspbb\x06proto3"

var (
	file_operations_proto_rawDescOnce sync.Once
	file_operations_proto_rawDescData []byte
)

func file_operations_proto_rawDescGZIP() []byte {
	file_operations_proto_rawDescOnce.Do(func() {
		file_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operations_proto_rawDesc), len(file_operations_proto_rawDesc)))
	})
	return file_operations_proto_rawDescData
}

var file_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_operations_proto_goTypes = []any{
	(*ProposeRequest)(nil),                 // 0: amh.operations.v1.ProposeRequest
	(*GetEffectRequest)(nil),               // 1: amh.operations.v1.GetEffectRequest
	(*ListEffectsByOperationRequest)(nil),  // 2: amh.operations.v1.ListEffectsByOperationRequest
	(*ListEffectsByOperationResponse)(nil), // 3: amh.operations.v1.ListEffectsByOperationResponse
	(*MarkDispatchPendingRequest)(nil),     // 4: amh.operations.v1.MarkDispatchPendingRequest
	(*MarkDispatchedRequest)(nil),          // 5: amh.operations.v1.MarkDispatchedRequest
	(*MarkObservedRequest)(nil),            // 6: amh.operations.v1.MarkObservedRequest
	(*MarkOutcomeUnknownRequest)(nil),      // 7: amh.operations.v1.MarkOutcomeUnknownRequest
	(*ResolveRequest)(nil),                 // 8: amh.operations.v1.ResolveRequest
	(*Effect)(nil),                         // 9: amh.operations.v1.Effect
}
var file_operations_proto_depIdxs = []int32{
	9, // 0: amh.operations.v1.ListEffectsByOperationResponse.effects:type_name -> amh.operations.v1.Effect
	0, // 1: amh.operations.v1.OperationsService.Propose:input_type -> amh.operations.v1.ProposeRequest
	1, // 2: amh.operations.v1.OperationsService.GetEffect:input_type -> amh.operations.v1.GetEffectRequest
	2, // 3: amh.operations.v1.OperationsService.ListEffectsByOperation:input_type -> amh.operations.v1.ListEffectsByOperationRequest
	4, // 4: amh.operations.v1.OperationsService.MarkDispatchPending:input_type -> amh.operations.v1.MarkDispatchPendingRequest
	5, // 5: amh.operations.v1.OperationsService.MarkDispatched:input_type -> amh.operations.v1.MarkDispatchedRequest
	6, // 6: amh.operations.v1.OperationsService.MarkObserved:input_type -> amh.operations.v1.MarkObservedRequest
	7, // 7: amh.operations.v1.OperationsService.MarkOutcomeUnknown:input_type -> amh.operations.v1.MarkOutcomeUnknownRequest
	8, // 8: amh.operations.v1.OperationsService.Resolve:input_type -> amh.operations.v1.ResolveRequest
	9, // 9: amh.operations.v1.OperationsService.Propose:output_type -> amh.operations.v1.Effect
	9, // 10: amh.operations.v1.OperationsService.GetEffect:output_type -> amh.operations.v1.Effect
	3, // 11: amh.operations.v1.OperationsService.ListEffectsByOperation:output_type -> amh.operations.v1.ListEffectsByOperationResponse
	9, // 12: amh.operations.v1.OperationsService.MarkDispatchPending:output_type -> amh.operations.v1.Effect
	9, // 13: amh.operations.v1.OperationsService.MarkDispatched:output_type -> amh.operations.v1.Effect
	9, // 14: amh.operations.v1.OperationsService.MarkObserved:output_type -> amh.operations.v1.Effect
	9, // 15: amh.operations.v1.OperationsService.MarkOutcomeUnknown:output_type -> amh.operations.v1.Effect
	9, // 16: amh.operations.v1.OperationsService.Resolve:output_type -> amh.operations.v1.Effect
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_operations_proto_init() }
func file_operations_proto_init() {
	if File_operations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operations_proto_rawDesc), len(file_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operations_proto_goTypes,
		DependencyIndexes: file_operations_proto_depIdxs,
		MessageInfos:      file_operations_proto_msgTypes,
	}.Build()
	File_operations_proto = out.File
	file_operations_proto_goTypes = nil
	file_operations_proto_depIdxs = nil
}
