// PolicyService — daemon/policy's generic fail-closed policy/approval seam
// (docs/AMH-SPECIFICATION.md §6), over gRPC instead of HTTP+JSON.
//
// This is Phase 1 of the gRPC migration scoped for the internal, purely
// synchronous Go-daemon <-> Python-cognition-worker call path (§3.1/§3.3:
// "local gRPC transport" / "local gRPC for synchronous daemon/worker
// calls"). policy has no browser (control-plane UI) caller and no
// external-protocol caller — every real consumer is Python agent code —
// which is exactly why it's the first service migrated: smallest surface,
// cleanest boundary, nothing else to keep working in parallel.
//
// payload fields stay JSON-encoded strings, not google.protobuf.Struct,
// deliberately: daemon/policy.Digest computes a canonical digest from the
// arbitrary caller-supplied payload, and the existing HTTP path already
// commits to json.Marshal's own byte representation for that digest. A
// second, different canonicalization (protobuf Struct's own field
// ordering/encoding rules) would make the same logical payload hash
// differently depending on which transport carried it — silently
// breaking §15 acceptance invariant #6 ("policy dispatch bound to the
// admitted action digest") for any caller that decided over one
// transport and consumed over the other. Carrying the exact same JSON
// bytes over gRPC keeps digest computation transport-agnostic.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: contracts/proto/policy.proto

package policypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Reversibility string                 `protobuf:"bytes,3,opt,name=reversibility,proto3" json:"reversibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_contracts_proto_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{0}
}

func (x *DecideRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DecideRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *DecideRequest) GetReversibility() string {
	if x != nil {
		return x.Reversibility
	}
	return ""
}

type GetDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecisionRequest) Reset() {
	*x = GetDecisionRequest{}
	mi := &file_contracts_proto_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionRequest) ProtoMessage() {}

func (x *GetDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetDecisionRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{1}
}

func (x *GetDecisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_contracts_proto_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *ConsumeRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_contracts_proto_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{3}
}

type ListPendingApprovalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsRequest) Reset() {
	*x = ListPendingApprovalsRequest{}
	mi := &file_contracts_proto_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsRequest) ProtoMessage() {}

func (x *ListPendingApprovalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{4}
}

type ListPendingApprovalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approvals     []*ApprovalRequest     `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsResponse) Reset() {
	*x = ListPendingApprovalsResponse{}
	mi := &file_contracts_proto_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsResponse) ProtoMessage() {}

func (x *ListPendingApprovalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{5}
}

func (x *ListPendingApprovalsResponse) GetApprovals() []*ApprovalRequest {
	if x != nil {
		return x.Approvals
	}
	return nil
}

type GetApprovalRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApprovalRequestRequest) Reset() {
	*x = GetApprovalRequestRequest{}
	mi := &file_contracts_proto_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApprovalRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovalRequestRequest) ProtoMessage() {}

func (x *GetApprovalRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovalRequestRequest.ProtoReflect.Descriptor instead.
func (*GetApprovalRequestRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{6}
}

func (x *GetApprovalRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	ResolvedBy    string                 `protobuf:"bytes,2,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveApprovalRequest) Reset() {
	*x = ResolveApprovalRequest{}
	mi := &file_contracts_proto_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveApprovalRequest) ProtoMessage() {}

func (x *ResolveApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveApprovalRequest.ProtoReflect.Descriptor instead.
func (*ResolveApprovalRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveApprovalRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ResolveApprovalRequest) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *ResolveApprovalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Decision struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OperationId       string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ActionDigest      string                 `protobuf:"bytes,3,opt,name=action_digest,json=actionDigest,proto3" json:"action_digest,omitempty"`
	PolicyId          string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion     string                 `protobuf:"bytes,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Result            string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	ReasonCodes       []string               `protobuf:"bytes,7,rep,name=reason_codes,json=reasonCodes,proto3" json:"reason_codes,omitempty"`
	ApprovalRequestId string                 `protobuf:"bytes,8,opt,name=approval_request_id,json=approvalRequestId,proto3" json:"approval_request_id,omitempty"`
	DecidedAt         string                 `protobuf:"bytes,9,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ConsumedAt        string                 `protobuf:"bytes,11,opt,name=consumed_at,json=consumedAt,proto3" json:"consumed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_contracts_proto_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{8}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Decision) GetActionDigest() string {
	if x != nil {
		return x.ActionDigest
	}
	return ""
}

func (x *Decision) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *Decision) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *Decision) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Decision) GetReasonCodes() []string {
	if x != nil {
		return x.ReasonCodes
	}
	return nil
}

func (x *Decision) GetApprovalRequestId() string {
	if x != nil {
		return x.ApprovalRequestId
	}
	return ""
}

func (x *Decision) GetDecidedAt() string {
	if x != nil {
		return x.DecidedAt
	}
	return ""
}

func (x *Decision) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Decision) GetConsumedAt() string {
	if x != nil {
		return x.ConsumedAt
	}
	return ""
}

type ApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ResolvedBy    string                 `protobuf:"bytes,4,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`
	ResolvedAt    string                 `protobuf:"bytes,5,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_contracts_proto_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_policy_proto_rawDescGZIP(), []int{9}
}

func (x *ApprovalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *ApprovalRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApprovalRequest) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *ApprovalRequest) GetResolvedAt() string {
	if x != nil {
		return x.ResolvedAt
	}
	return ""
}

func (x *ApprovalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_contracts_proto_policy_proto protoreflect.FileDescriptor

const file_contracts_proto_policy_proto_rawDesc = "" +
	"\n" +
	"\x1ccontracts/proto/policy.proto\x12\ramh.policy.v1\"{\n" +
	"\rDecideRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\x12$\n" +
	"\rreversibility\x18\x03 \x01(\tR\rreversibility\"$\n" +
	"\x12GetDecisionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x0eConsumeRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"\x11\n" +
	"\x0fConsumeResponse\"\x1d\n" +
	"\x1bListPendingApprovalsRequest\"\\\n" +
	"\x1cListPendingApprovalsResponse\x12<\n" +
	"\tapprovals\x18\x01 \x03(\v2\x1e.amh.policy.v1.ApprovalRequestR\tapprovals\"+\n" +
	"\x19GetApprovalRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"r\n" +
	"\x16ResolveApprovalRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1f\n" +
	"\vresolved_by\x18\x02 \x01(\tR\n" +
	"resolvedBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xf0\x02\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12#\n" +
	"\raction_digest\x18\x03 \x01(\tR\factionDigest\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x05 \x01(\tR\rpolicyVersion\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12!\n" +
	"\freason_codes\x18\a \x03(\tR\vreasonCodes\x12.\n" +
	"\x13approval_request_id\x18\b \x01(\tR\x11approvalRequestId\x12\x1d\n" +
	"\n" +
	"decided_at\x18\t \x01(\tR\tdecidedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\x12\x1f\n" +
	"\vconsumed_at\x18\v \x01(\tR\n" +
	"consumedAt\"\xb4\x01\n" +
	"\x0fApprovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vresolved_by\x18\x04 \x01(\tR\n" +
	"resolvedBy\x12\x1f\n" +
	"\vresolved_at\x18\x05 \x01(\tR\n" +
	"resolvedAt\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason2\xd0\x04\n" +
	"\rPolicyService\x12?\n" +
	"\x06Decide\x12\x1c.amh.policy.v1.DecideRequest\x1a\x17.amh.policy.v1.Decision\x12I\n" +
	"\vGetDecision\x12!.amh.policy.v1.GetDecisionRequest\x1a\x17.amh.policy.v1.Decision\x12H\n" +
	"\aConsume\x12\x1d.amh.policy.v1.ConsumeRequest\x1a\x1e.amh.policy.v1.ConsumeResponse\x12o\n" +
	"\x14ListPendingApprovals\x12*.amh.policy.v1.ListPendingApprovalsRequest\x1a+.amh.policy.v1.ListPendingApprovalsResponse\x12^\n" +
	"\x12GetApprovalRequest\x12(.amh.policy.v1.GetApprovalRequestRequest\x1a\x1e.amh.policy.v1.ApprovalRequest\x12I\n" +
	"\aApprove\x12%.amh.policy.v1.ResolveApprovalRequest\x1a\x17.amh.policy.v1.Decision\x12M\n" +
	"\x04Deny\x12%.amh.policy.v1.ResolveApprovalRequest\x1a\x1e.amh.policy.v1.ApprovalRequestBKZIgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/policypbb\x06proto3"

var (
	file_contracts_proto_policy_proto_rawDescOnce sync.Once
	file_contracts_proto_policy_proto_rawDescData []byte
)

func file_contracts_proto_policy_proto_rawDescGZIP() []byte {
	file_contracts_proto_policy_proto_rawDescOnce.Do(func() {
		file_contracts_proto_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_policy_proto_rawDesc), len(file_contracts_proto_policy_proto_rawDesc)))
	})
	return file_contracts_proto_policy_proto_rawDescData
}

var file_contracts_proto_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_contracts_proto_policy_proto_goTypes = []any{
	(*DecideRequest)(nil),                // 0: amh.policy.v1.DecideRequest
	(*GetDecisionRequest)(nil),           // 1: amh.policy.v1.GetDecisionRequest
	(*ConsumeRequest)(nil),               // 2: amh.policy.v1.ConsumeRequest
	(*ConsumeResponse)(nil),              // 3: amh.policy.v1.ConsumeResponse
	(*ListPendingApprovalsRequest)(nil),  // 4: amh.policy.v1.ListPendingApprovalsRequest
	(*ListPendingApprovalsResponse)(nil), // 5: amh.policy.v1.ListPendingApprovalsResponse
	(*GetApprovalRequestRequest)(nil),    // 6: amh.policy.v1.GetApprovalRequestRequest
	(*ResolveApprovalRequest)(nil),       // 7: amh.policy.v1.ResolveApprovalRequest
	(*Decision)(nil),                     // 8: amh.policy.v1.Decision
	(*ApprovalRequest)(nil),              // 9: amh.policy.v1.ApprovalRequest
}
var file_contracts_proto_policy_proto_depIdxs = []int32{
	9, // 0: amh.policy.v1.ListPendingApprovalsResponse.approvals:type_name -> amh.policy.v1.ApprovalRequest
	0, // 1: amh.policy.v1.PolicyService.Decide:input_type -> amh.policy.v1.DecideRequest
	1, // 2: amh.policy.v1.PolicyService.GetDecision:input_type -> amh.policy.v1.GetDecisionRequest
	2, // 3: amh.policy.v1.PolicyService.Consume:input_type -> amh.policy.v1.ConsumeRequest
	4, // 4: amh.policy.v1.PolicyService.ListPendingApprovals:input_type -> amh.policy.v1.ListPendingApprovalsRequest
	6, // 5: amh.policy.v1.PolicyService.GetApprovalRequest:input_type -> amh.policy.v1.GetApprovalRequestRequest
	7, // 6: amh.policy.v1.PolicyService.Approve:input_type -> amh.policy.v1.ResolveApprovalRequest
	7, // 7: amh.policy.v1.PolicyService.Deny:input_type -> amh.policy.v1.ResolveApprovalRequest
	8, // 8: amh.policy.v1.PolicyService.Decide:output_type -> amh.policy.v1.Decision
	8, // 9: amh.policy.v1.PolicyService.GetDecision:output_type -> amh.policy.v1.Decision
	3, // 10: amh.policy.v1.PolicyService.Consume:output_type -> amh.policy.v1.ConsumeResponse
	5, // 11: amh.policy.v1.PolicyService.ListPendingApprovals:output_type -> amh.policy.v1.ListPendingApprovalsResponse
	9, // 12: amh.policy.v1.PolicyService.GetApprovalRequest:output_type -> amh.policy.v1.ApprovalRequest
	8, // 13: amh.policy.v1.PolicyService.Approve:output_type -> amh.policy.v1.Decision
	9, // 14: amh.policy.v1.PolicyService.Deny:output_type -> amh.policy.v1.ApprovalRequest
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contracts_proto_policy_proto_init() }
func file_contracts_proto_policy_proto_init() {
	if File_contracts_proto_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_policy_proto_rawDesc), len(file_contracts_proto_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_proto_policy_proto_goTypes,
		DependencyIndexes: file_contracts_proto_policy_proto_depIdxs,
		MessageInfos:      file_contracts_proto_policy_proto_msgTypes,
	}.Build()
	File_contracts_proto_policy_proto = out.File
	file_contracts_proto_policy_proto_goTypes = nil
	file_contracts_proto_policy_proto_depIdxs = nil
}
