// PolicyService — daemon/policy's generic fail-closed policy/approval seam
// (docs/AMH-SPECIFICATION.md §6), over gRPC instead of HTTP+JSON.
//
// This is Phase 1 of the gRPC migration scoped for the internal, purely
// synchronous Go-daemon <-> Python-cognition-worker call path (§3.1/§3.3:
// "local gRPC transport" / "local gRPC for synchronous daemon/worker
// calls"). policy has no browser (control-plane UI) caller and no
// external-protocol caller — every real consumer is Python agent code —
// which is exactly why it's the first service migrated: smallest surface,
// cleanest boundary, nothing else to keep working in parallel.
//
// payload fields stay JSON-encoded strings, not google.protobuf.Struct,
// deliberately: daemon/policy.Digest computes a canonical digest from the
// arbitrary caller-supplied payload, and the existing HTTP path already
// commits to json.Marshal's own byte representation for that digest. A
// second, different canonicalization (protobuf Struct's own field
// ordering/encoding rules) would make the same logical payload hash
// differently depending on which transport carried it — silently
// breaking §15 acceptance invariant #6 ("policy dispatch bound to the
// admitted action digest") for any caller that decided over one
// transport and consumed over the other. Carrying the exact same JSON
// bytes over gRPC keeps digest computation transport-agnostic.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: contracts/proto/policy.proto

package policypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyService_Decide_FullMethodName               = "/amh.policy.v1.PolicyService/Decide"
	PolicyService_GetDecision_FullMethodName          = "/amh.policy.v1.PolicyService/GetDecision"
	PolicyService_Consume_FullMethodName              = "/amh.policy.v1.PolicyService/Consume"
	PolicyService_ListPendingApprovals_FullMethodName = "/amh.policy.v1.PolicyService/ListPendingApprovals"
	PolicyService_GetApprovalRequest_FullMethodName   = "/amh.policy.v1.PolicyService/GetApprovalRequest"
	PolicyService_Approve_FullMethodName              = "/amh.policy.v1.PolicyService/Approve"
	PolicyService_Deny_FullMethodName                 = "/amh.policy.v1.PolicyService/Deny"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyServiceClient interface {
	// Decide admits or defers req through the one built-in policy —
	// mirrors POST /v1/policy/decide.
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*Decision, error)
	// GetDecision is a cheap, idempotent read — mirrors
	// GET /v1/policy/decisions/{decisionID}.
	GetDecision(ctx context.Context, in *GetDecisionRequest, opts ...grpc.CallOption) (*Decision, error)
	// Consume binds dispatch to the exact digest of payload_json, failing
	// closed on any mismatch, expiry, or already-consumed decision —
	// mirrors POST /v1/policy/decisions/{decisionID}/consume.
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error)
	// ListPendingApprovals — mirrors GET /v1/policy/approvals.
	ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListPendingApprovalsResponse, error)
	// GetApprovalRequest — mirrors GET /v1/policy/approvals/{approvalID}.
	GetApprovalRequest(ctx context.Context, in *GetApprovalRequestRequest, opts ...grpc.CallOption) (*ApprovalRequest, error)
	// Approve is operator-only (enforced by the auth interceptor, the same
	// anti-self-approval property daemon/authn's RequireRole already
	// enforces over HTTP) — mirrors
	// POST /v1/policy/approvals/{approvalID}/approve.
	Approve(ctx context.Context, in *ResolveApprovalRequest, opts ...grpc.CallOption) (*Decision, error)
	// Deny is operator-only — mirrors
	// POST /v1/policy/approvals/{approvalID}/deny.
	Deny(ctx context.Context, in *ResolveApprovalRequest, opts ...grpc.CallOption) (*ApprovalRequest, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, PolicyService_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) GetDecision(ctx context.Context, in *GetDecisionRequest, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, PolicyService_GetDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeResponse)
	err := c.cc.Invoke(ctx, PolicyService_Consume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListPendingApprovalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingApprovalsResponse)
	err := c.cc.Invoke(ctx, PolicyService_ListPendingApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) GetApprovalRequest(ctx context.Context, in *GetApprovalRequestRequest, opts ...grpc.CallOption) (*ApprovalRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalRequest)
	err := c.cc.Invoke(ctx, PolicyService_GetApprovalRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) Approve(ctx context.Context, in *ResolveApprovalRequest, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, PolicyService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) Deny(ctx context.Context, in *ResolveApprovalRequest, opts ...grpc.CallOption) (*ApprovalRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalRequest)
	err := c.cc.Invoke(ctx, PolicyService_Deny_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations must embed UnimplementedPolicyServiceServer
// for forward compatibility.
type PolicyServiceServer interface {
	// Decide admits or defers req through the one built-in policy —
	// mirrors POST /v1/policy/decide.
	Decide(context.Context, *DecideRequest) (*Decision, error)
	// GetDecision is a cheap, idempotent read — mirrors
	// GET /v1/policy/decisions/{decisionID}.
	GetDecision(context.Context, *GetDecisionRequest) (*Decision, error)
	// Consume binds dispatch to the exact digest of payload_json, failing
	// closed on any mismatch, expiry, or already-consumed decision —
	// mirrors POST /v1/policy/decisions/{decisionID}/consume.
	Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error)
	// ListPendingApprovals — mirrors GET /v1/policy/approvals.
	ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListPendingApprovalsResponse, error)
	// GetApprovalRequest — mirrors GET /v1/policy/approvals/{approvalID}.
	GetApprovalRequest(context.Context, *GetApprovalRequestRequest) (*ApprovalRequest, error)
	// Approve is operator-only (enforced by the auth interceptor, the same
	// anti-self-approval property daemon/authn's RequireRole already
	// enforces over HTTP) — mirrors
	// POST /v1/policy/approvals/{approvalID}/approve.
	Approve(context.Context, *ResolveApprovalRequest) (*Decision, error)
	// Deny is operator-only — mirrors
	// POST /v1/policy/approvals/{approvalID}/deny.
	Deny(context.Context, *ResolveApprovalRequest) (*ApprovalRequest, error)
	mustEmbedUnimplementedPolicyServiceServer()
}

// UnimplementedPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) Decide(context.Context, *DecideRequest) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedPolicyServiceServer) GetDecision(context.Context, *GetDecisionRequest) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecision not implemented")
}
func (UnimplementedPolicyServiceServer) Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedPolicyServiceServer) ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListPendingApprovalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingApprovals not implemented")
}
func (UnimplementedPolicyServiceServer) GetApprovalRequest(context.Context, *GetApprovalRequestRequest) (*ApprovalRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApprovalRequest not implemented")
}
func (UnimplementedPolicyServiceServer) Approve(context.Context, *ResolveApprovalRequest) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedPolicyServiceServer) Deny(context.Context, *ResolveApprovalRequest) (*ApprovalRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method Deny not implemented")
}
func (UnimplementedPolicyServiceServer) mustEmbedUnimplementedPolicyServiceServer() {}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue()                       {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_GetDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).GetDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_GetDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).GetDecision(ctx, req.(*GetDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_Consume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).Consume(ctx, req.(*ConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_ListPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ListPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_ListPendingApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ListPendingApprovals(ctx, req.(*ListPendingApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_GetApprovalRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApprovalRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).GetApprovalRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_GetApprovalRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).GetApprovalRequest(ctx, req.(*GetApprovalRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).Approve(ctx, req.(*ResolveApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_Deny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).Deny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_Deny_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).Deny(ctx, req.(*ResolveApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amh.policy.v1.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decide",
			Handler:    _PolicyService_Decide_Handler,
		},
		{
			MethodName: "GetDecision",
			Handler:    _PolicyService_GetDecision_Handler,
		},
		{
			MethodName: "Consume",
			Handler:    _PolicyService_Consume_Handler,
		},
		{
			MethodName: "ListPendingApprovals",
			Handler:    _PolicyService_ListPendingApprovals_Handler,
		},
		{
			MethodName: "GetApprovalRequest",
			Handler:    _PolicyService_GetApprovalRequest_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _PolicyService_Approve_Handler,
		},
		{
			MethodName: "Deny",
			Handler:    _PolicyService_Deny_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/proto/policy.proto",
}
