# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x10\x61mh.inference.v1\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x96\x01\n\x0f\x43ompleteRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x11\n\tproviders\x18\x02 \x03(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0e\n\x06system\x18\x04 \x01(\t\x12+\n\x08messages\x18\x05 \x03(\x0b\x32\x19.amh.inference.v1.Message\x12\x12\n\nmax_tokens\x18\x06 \x01(\x05\"_\n\x10\x43ompleteResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0cinput_tokens\x18\x02 \x01(\x05\x12\x15\n\routput_tokens\x18\x03 \x01(\x05\x12\x10\n\x08\x63ost_usd\x18\x04 \x01(\x01\"+\n\x13\x43ountTokensResponse\x12\x14\n\x0cinput_tokens\x18\x01 \x01(\x05\"Q\n\x0c\x45mbedRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x11\n\tproviders\x18\x02 \x03(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\r\n\x05input\x18\x04 \x03(\t\"\"\n\x10\x45mbedFloatVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"Z\n\rEmbedResponse\x12\x36\n\nembeddings\x18\x01 \x03(\x0b\x32\".amh.inference.v1.EmbedFloatVector\x12\x11\n\tdimension\x18\x02 \x01(\x05\x32\x88\x02\n\x10InferenceService\x12Q\n\x08\x43omplete\x12!.amh.inference.v1.CompleteRequest\x1a\".amh.inference.v1.CompleteResponse\x12W\n\x0b\x43ountTokens\x12!.amh.inference.v1.CompleteRequest\x1a%.amh.inference.v1.CountTokensResponse\x12H\n\x05\x45mbed\x12\x1e.amh.inference.v1.EmbedRequest\x1a\x1f.amh.inference.v1.EmbedResponseBNZLgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/inferencepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZLgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/inferencepb'
  _globals['_MESSAGE']._serialized_start=37
  _globals['_MESSAGE']._serialized_end=77
  _globals['_COMPLETEREQUEST']._serialized_start=80
  _globals['_COMPLETEREQUEST']._serialized_end=230
  _globals['_COMPLETERESPONSE']._serialized_start=232
  _globals['_COMPLETERESPONSE']._serialized_end=327
  _globals['_COUNTTOKENSRESPONSE']._serialized_start=329
  _globals['_COUNTTOKENSRESPONSE']._serialized_end=372
  _globals['_EMBEDREQUEST']._serialized_start=374
  _globals['_EMBEDREQUEST']._serialized_end=455
  _globals['_EMBEDFLOATVECTOR']._serialized_start=457
  _globals['_EMBEDFLOATVECTOR']._serialized_end=491
  _globals['_EMBEDRESPONSE']._serialized_start=493
  _globals['_EMBEDRESPONSE']._serialized_end=583
  _globals['_INFERENCESERVICE']._serialized_start=586
  _globals['_INFERENCESERVICE']._serialized_end=850
# @@protoc_insertion_point(module_scope)
