# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Complete = channel.unary_unary(
                '/amh.inference.v1.InferenceService/Complete',
                request_serializer=inference__pb2.CompleteRequest.SerializeToString,
                response_deserializer=inference__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.CountTokens = channel.unary_unary(
                '/amh.inference.v1.InferenceService/CountTokens',
                request_serializer=inference__pb2.CompleteRequest.SerializeToString,
                response_deserializer=inference__pb2.CountTokensResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/amh.inference.v1.InferenceService/Embed',
                request_serializer=inference__pb2.EmbedRequest.SerializeToString,
                response_deserializer=inference__pb2.EmbedResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Complete(self, request, context):
        """Complete — mirrors POST /v1/inference/complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountTokens(self, request, context):
        """CountTokens — mirrors POST /v1/inference/count-tokens. Only
        implemented daemon-side for the anthropic provider kind.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Embed — mirrors POST /v1/inference/embed. Only implemented
        daemon-side for the openai_compatible provider kind.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=inference__pb2.CompleteRequest.FromString,
                    response_serializer=inference__pb2.CompleteResponse.SerializeToString,
            ),
            'CountTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.CountTokens,
                    request_deserializer=inference__pb2.CompleteRequest.FromString,
                    response_serializer=inference__pb2.CountTokensResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=inference__pb2.EmbedRequest.FromString,
                    response_serializer=inference__pb2.EmbedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'amh.inference.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('amh.inference.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.inference.v1.InferenceService/Complete',
            inference__pb2.CompleteRequest.SerializeToString,
            inference__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.inference.v1.InferenceService/CountTokens',
            inference__pb2.CompleteRequest.SerializeToString,
            inference__pb2.CountTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/amh.inference.v1.InferenceService/Embed',
            inference__pb2.EmbedRequest.SerializeToString,
            inference__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
