// InferenceService — daemon/inference's model-provider seam
// (docs/AMH-SPECIFICATION.md §2.1), over gRPC instead of HTTP+JSON.
//
// Phase 4 (final phase) of the gRPC migration (see contracts/proto/
// policy.proto's header comment for the migration's overall scope/
// rationale). Deliberately last: this is the hottest, highest-volume call
// path in the whole daemon (every model completion, token count, and
// embedding call an agent makes) and the one with the largest blast
// radius if something regresses — every other internal service moved
// first so this final cutover has the least amount still changing under
// it. Migrates exactly the three routes daemon/api/controlplane.go's own
// "Inference (the model-provider seam)" section documents as the
// AMH-native wire shape (/v1/inference/complete, /v1/inference/count-tokens,
// /v1/inference/embed) — NOT the separate /v1/openai/chat/completions and
// /v1/openai/embeddings facade routes, which exist specifically so an
// external service that only speaks the OpenAI HTTP wire format (e.g.
// Hindsight's HINDSIGHT_API_LLM_BASE_URL) can be pointed at this daemon
// without writing an AMH-specific client; those have an inherently
// external caller and stay on daemon/api's HTTP surface exactly like
// every other browser/external-protocol route this migration has left
// alone (control-plane UI, A2A/MCP, accounts/computers/extensions).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: inference.proto

package inferencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CompleteRequest doubles as CountTokens' request (max_tokens is simply
// ignored there) — the same reuse daemon/api/controlplane.go's HTTP
// handlers already make (handleInferenceCountTokens decodes the same
// inferenceCompleteRequest handleInferenceComplete does).
type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Providers     []string               `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	System        string                 `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	Messages      []*Message             `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CompleteRequest) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *CompleteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CompleteRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	InputTokens   int32                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CompleteResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *CompleteResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type CountTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensResponse) Reset() {
	*x = CountTokensResponse{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensResponse) ProtoMessage() {}

func (x *CountTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensResponse.ProtoReflect.Descriptor instead.
func (*CountTokensResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *CountTokensResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Providers     []string               `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Input         []string               `protobuf:"bytes,4,rep,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmbedRequest) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedRequest) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

type EmbedFloatVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedFloatVector) Reset() {
	*x = EmbedFloatVector{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedFloatVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedFloatVector) ProtoMessage() {}

func (x *EmbedFloatVector) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedFloatVector.ProtoReflect.Descriptor instead.
func (*EmbedFloatVector) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

func (x *EmbedFloatVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbedFloatVector    `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedResponse) GetEmbeddings() []*EmbedFloatVector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbedResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x10amh.inference.v1\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xcf\x01\n" +
	"\x0fCompleteRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\tproviders\x18\x02 \x03(\tR\tproviders\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06system\x18\x04 \x01(\tR\x06system\x125\n" +
	"\bmessages\x18\x05 \x03(\v2\x19.amh.inference.v1.MessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\"n\n" +
	"\x10CompleteResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x05R\foutputTokens\"8\n" +
	"\x13CountTokensResponse\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\"t\n" +
	"\fEmbedRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\tproviders\x18\x02 \x03(\tR\tproviders\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x14\n" +
	"\x05input\x18\x04 \x03(\tR\x05input\"*\n" +
	"\x10EmbedFloatVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"q\n" +
	"\rEmbedResponse\x12B\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\".amh.inference.v1.EmbedFloatVectorR\n" +
	"embeddings\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension2\x88\x02\n" +
	"\x10InferenceService\x12Q\n" +
	"\bComplete\x12!.amh.inference.v1.CompleteRequest\x1a\".amh.inference.v1.CompleteResponse\x12W\n" +
	"\vCountTokens\x12!.amh.inference.v1.CompleteRequest\x1a%.amh.inference.v1.CountTokensResponse\x12H\n" +
	"\x05Embed\x12\x1e.amh.inference.v1.EmbedRequest\x1a\x1f.amh.inference.v1.EmbedResponseBNZLgithub.com/AtonoRobotics/Autonomous-Agent-Habitat/daemon/grpcapi/inferencepbb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_inference_proto_goTypes = []any{
	(*Message)(nil),             // 0: amh.inference.v1.Message
	(*CompleteRequest)(nil),     // 1: amh.inference.v1.CompleteRequest
	(*CompleteResponse)(nil),    // 2: amh.inference.v1.CompleteResponse
	(*CountTokensResponse)(nil), // 3: amh.inference.v1.CountTokensResponse
	(*EmbedRequest)(nil),        // 4: amh.inference.v1.EmbedRequest
	(*EmbedFloatVector)(nil),    // 5: amh.inference.v1.EmbedFloatVector
	(*EmbedResponse)(nil),       // 6: amh.inference.v1.EmbedResponse
}
var file_inference_proto_depIdxs = []int32{
	0, // 0: amh.inference.v1.CompleteRequest.messages:type_name -> amh.inference.v1.Message
	5, // 1: amh.inference.v1.EmbedResponse.embeddings:type_name -> amh.inference.v1.EmbedFloatVector
	1, // 2: amh.inference.v1.InferenceService.Complete:input_type -> amh.inference.v1.CompleteRequest
	1, // 3: amh.inference.v1.InferenceService.CountTokens:input_type -> amh.inference.v1.CompleteRequest
	4, // 4: amh.inference.v1.InferenceService.Embed:input_type -> amh.inference.v1.EmbedRequest
	2, // 5: amh.inference.v1.InferenceService.Complete:output_type -> amh.inference.v1.CompleteResponse
	3, // 6: amh.inference.v1.InferenceService.CountTokens:output_type -> amh.inference.v1.CountTokensResponse
	6, // 7: amh.inference.v1.InferenceService.Embed:output_type -> amh.inference.v1.EmbedResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
