// InferenceService — daemon/inference's model-provider seam
// (docs/AMH-SPECIFICATION.md §2.1), over gRPC instead of HTTP+JSON.
//
// Phase 4 (final phase) of the gRPC migration (see contracts/proto/
// policy.proto's header comment for the migration's overall scope/
// rationale). Deliberately last: this is the hottest, highest-volume call
// path in the whole daemon (every model completion, token count, and
// embedding call an agent makes) and the one with the largest blast
// radius if something regresses — every other internal service moved
// first so this final cutover has the least amount still changing under
// it. Migrates exactly the three routes daemon/api/controlplane.go's own
// "Inference (the model-provider seam)" section documents as the
// AMH-native wire shape (/v1/inference/complete, /v1/inference/count-tokens,
// /v1/inference/embed) — NOT the separate /v1/openai/chat/completions and
// /v1/openai/embeddings facade routes, which exist specifically so an
// external service that only speaks the OpenAI HTTP wire format (e.g.
// Hindsight's HINDSIGHT_API_LLM_BASE_URL) can be pointed at this daemon
// without writing an AMH-specific client; those have an inherently
// external caller and stay on daemon/api's HTTP surface exactly like
// every other browser/external-protocol route this migration has left
// alone (control-plane UI, A2A/MCP, accounts/computers/extensions).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: inference.proto

package inferencepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceService_Complete_FullMethodName    = "/amh.inference.v1.InferenceService/Complete"
	InferenceService_CountTokens_FullMethodName = "/amh.inference.v1.InferenceService/CountTokens"
	InferenceService_Embed_FullMethodName       = "/amh.inference.v1.InferenceService/Embed"
)

// InferenceServiceClient is the client API for InferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceServiceClient interface {
	// Complete — mirrors POST /v1/inference/complete.
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// CountTokens — mirrors POST /v1/inference/count-tokens. Only
	// implemented daemon-side for the anthropic provider kind.
	CountTokens(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CountTokensResponse, error)
	// Embed — mirrors POST /v1/inference/embed. Only implemented
	// daemon-side for the openai_compatible provider kind.
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, InferenceService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) CountTokens(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CountTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountTokensResponse)
	err := c.cc.Invoke(ctx, InferenceService_CountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, InferenceService_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServiceServer is the server API for InferenceService service.
// All implementations must embed UnimplementedInferenceServiceServer
// for forward compatibility.
type InferenceServiceServer interface {
	// Complete — mirrors POST /v1/inference/complete.
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// CountTokens — mirrors POST /v1/inference/count-tokens. Only
	// implemented daemon-side for the anthropic provider kind.
	CountTokens(context.Context, *CompleteRequest) (*CountTokensResponse, error)
	// Embed — mirrors POST /v1/inference/embed. Only implemented
	// daemon-side for the openai_compatible provider kind.
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedInferenceServiceServer) CountTokens(context.Context, *CompleteRequest) (*CountTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountTokens not implemented")
}
func (UnimplementedInferenceServiceServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}
func (UnimplementedInferenceServiceServer) testEmbeddedByValue()                          {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceServer will
// result in compilation errors.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_CountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).CountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_CountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).CountTokens(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amh.inference.v1.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _InferenceService_Complete_Handler,
		},
		{
			MethodName: "CountTokens",
			Handler:    _InferenceService_CountTokens_Handler,
		},
		{
			MethodName: "Embed",
			Handler:    _InferenceService_Embed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference.proto",
}
